"""
Django settings for autozone project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import importlib.util

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    def load_dotenv(*args, **kwargs):
        return False


def load_simple_env(env_path):
    if not Path(env_path).exists():
        return

    with open(env_path, encoding='utf-8') as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            os.environ[key.strip()] = value.strip()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_file = BASE_DIR / '.env'
if not load_dotenv(env_file, override=True):
    load_simple_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-f3a5%s@=t4u293zj+ad-i*^342ce22b+=wq$vj6@o_b(l!92po')

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.getenv('DJANGO_ENV', 'local').strip().lower()
DEBUG = DJANGO_ENV != 'production'

ALLOWED_HOSTS = ['autozonepro.org', 'www.autozonepro.org', '185.27.135.97', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'website',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autozone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autozone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_name = os.getenv('DB_NAME', '').strip()
db_user = os.getenv('DB_USER', '').strip()
db_password = os.getenv('DB_PASSWORD', '').strip()
db_host = os.getenv('DB_HOST', '').strip()
db_port = os.getenv('DB_PORT', '').strip()
has_mysql_driver = importlib.util.find_spec('MySQLdb') is not None

if all([db_name, db_user, db_password, db_host, db_port]) and has_mysql_driver:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ERPNext catalog integration
ERPNEXT_BASE_URL = os.getenv('ERPNEXT_BASE_URL', '').rstrip('/')
ERPNEXT_AUTH_TOKEN = os.getenv('ERPNEXT_AUTH_TOKEN', '').strip()
ERPNEXT_API_KEY = os.getenv('ERPNEXT_API_KEY', os.getenv('ERP_API_KEY', '')).strip()
ERPNEXT_API_SECRET = os.getenv('ERPNEXT_API_SECRET', os.getenv('ERP_API_SECRET', '')).strip()
ERPNEXT_ITEM_PRICE_LIST = os.getenv('ERPNEXT_ITEM_PRICE_LIST', '').strip()
ERPNEXT_ITEM_MODEL_FIELD = os.getenv('ERPNEXT_ITEM_MODEL_FIELD', 'item_group').strip() or 'item_group'
ERPNEXT_CATALOG_CACHE_TIMEOUT = int(os.getenv('ERPNEXT_CATALOG_CACHE_TIMEOUT', '300'))
ERPNEXT_VERIFY_SSL = os.getenv('ERPNEXT_VERIFY_SSL', 'false').strip().lower() in ('1', 'true', 'yes')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
